let tasks = [
  {
    id: 1,
    name: "Leanne Graham",
    username: "Bret",
    email: "bret@123",
  },
  {
    id: 2,
    name: "Ervin Howell",
    username: "Antonette",
    email: "shanna@123",
  },
  {
    id: 3,
    name: "Clementine Bauch",
    username: "Samantha",
    email: "nathan@123",
  },
  {
    id: 4,
    name: "Patricia Lebsack",
    username: "Karianne",
    email: "julianne@123",
  },
  {
    id: 5,
    name: "Chelsey Dietrich",
    username: "Kamren",
    email: "lucio@123",
  },
  {
    id: 6,
    name: "Mrs. Dennis Schulist",
    username: "Leopoldo_Corkery",
    email: "karley@123",
  },
  {
    id: 7,
    name: "Kurtis Weissnat",
    username: "Elwyn.Skiles",
    email: "telly@123",
  },
  {
    id: 8,
    name: "Nicholas Runolfsdottir V",
    username: "Maxime_Nienow",
    email: "sherwood@123",
  },
  {
    id: 9,
    name: "Glenna Reichert",
    username: "Delphine",
    email: "chaim@123",
  },
  {
    id: 10,
    name: "Clementina DuBuque",
    username: "Moriah.Stanton",
    email: "rey@123",
  },
  {
    id: 11,
    name: "Clementina ABC",
    username: "Moriah.Stanton",
    email: "rey123@123",
  },
  {
    id: 12,
    name: "Clementina XYZ",
    username: "Moriah.Stanton",
    email: "rey123@123",
  },
  {
    id: 13,
    name: "Clementina PQR",
    username: "Moriah.Stanton",
    email: "rey123@123",
  },
  {
    id: 14,
    name: "Clementina LMN",
    username: "Moriah.Stanton",
    email: "rey123@123",
  },
  {
    id: 15,
    name: "Clementina EFG",
    username: "Moriah.Stanton",
    email: "rey123@123",
  },
  {
    id: 16,
    name: "Clementina HIJ",
    username: "Moriah.Stanton",
    email: "rey123@123",
  },
  {
    id: 17,
    name: "Clementina KLM",
    username: "Moriah.Stanton",
    email: "rey123@123",
  },
  {
    id: 18,
    name: "Clementina NOP",
    username: "Moriah.Stanton",
    email: "rey123@123",
  },
  {
    id: 19,
    name: "Clementina QRS",
    username: "Moriah.Stanton",
    email: "rey123@123",
  },
  {
    id: 20,
    name: "Clementina TUV",
    username: "Moriah.Stanton",
    email: "rey123@123",
  },
  {
    id: 21,
    name: "Clementina WXY",
    username: "Moriah.Stanton",
    email: "rey123@123",
  },
  {
    id: 22,
    name: "Clementina ZZZ",
    username: "Moriah.Stanton",
    email: "rey123@123",
  },
  {
    id: 23,
    name: "Clementina AAA",
    username: "Moriah.Stanton",
    email: "rey123@123",
  },
  {
    id: 24,
    name: "Clementina BBB",
    username: "Moriah.Stanton",
    email: "rey123@",
  },
];

export default tasks;
